name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn version (4.5.0)
        run: corepack prepare yarn@4.5.0 --activate

      - name: Install dependencies
        run: yarn install

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          yarn global add vercel
          for project in packages/*/; do
            if [ -f "$project/package.json" ] && grep -q '"next":' "$project/package.json"; then
              project_name=$(basename $project)
              cd $project
              vercel --token $VERCEL_TOKEN --prod
              cd ../..
            fi
          done
