name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn version (4.5.0)
        run: corepack prepare yarn@4.5.0 --activate

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn workspace ox build
