name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn version (4.5.0)
        run: corepack prepare yarn@4.5.0 --activate

      - name: Build and push Docker image
        run: |
          # Dockerfile 경로가 프로젝트 루트가 아니라면, 경로를 명시합니다.
          # 예: -f ./your_project_directory/Dockerfile
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-app:${{ github.sha }} -f ./Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/your-app:${{ github.sha }}

      - name: Deploy to Vercel
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
